//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpCrawler2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public string ID { get; set; }
        public string SongName { get; set; }
        public string BandName { get; set; }
        public string FileName { get; set; }
        public string Favorite { get; set; }
    }
}
